server:
  port: 8888
  tomcat:
          uri-encoding: UTF-8
#spring
spring:
  devtools:
    restart:
      enabled: false

  #DATABASE CONFIG
  datasource:
    type: com.mchange.v2.c3p0.ComboPooledDataSource
    data: classpath:/db/data-mysql.sql
    url: jdbc:mysql://localhost:3306/decisionsupport?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    platform: mysql
#    initialization-mode: always
#    initialize: true
    continue-on-error: true
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
      timeout: 0

